name: i2dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv
  - numpy
  - matplotlib
  - pandas
  - pillow
  - plyfile
  - scipy
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.7.1+cu118
    - torchvision==0.22.1+cu118
    - torchaudio==2.7.1+cu118
    - triton
    - torch-scatter
    - absl-py
    - antlr4-python3-runtime
    - colorama
    - configargparse
    - contourpy
    - cycler
    - einops
    - filelock
    - fonttools
    - jaxtyping
    - jinja2
    - kiwisolver
    - kornia
    - kornia-rs
    - markdown
    - markupsafe
    - mpmath
    - networkx
    - ninja
    - protobuf
    - pyparsing
    - six
    - sympy
    - tensorboard
    - tensorboard-data-server
    - tqdm
    - typing-extensions
    - werkzeug
